import type { CollectionConfig } from 'payload'

export const EventLog: CollectionConfig = {
  slug: 'event-log',
  labels: { singular: 'Событие', plural: 'Журнал событий' },
  admin: {
    defaultColumns: ['eventType', 'owner', 'entityType', 'entityId', 'createdAt'],
    listSearchableFields: ['eventType', 'entityType', 'entityId'],
  },
  access: {
    read: ({ req: { user } }) => user?.role === 'admin',
    create: () => true,
    update: () => false,
    delete: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    {
      name: 'owner',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'eventType',
      type: 'select',
      label: 'Тип события',
      required: true,
      options: [
        { label: 'Вход', value: 'auth.login' },
        { label: 'Выход', value: 'auth.logout' },
        { label: 'Запрос доступа', value: 'access.request' },
        { label: 'Инвайт использован', value: 'invite.used' },
        { label: 'Онбординг: старт анализа', value: 'onboarding.analysis_start' },
        { label: 'Онбординг: анализ завершён', value: 'onboarding.analysis_complete' },
        { label: 'Онбординг: завершён', value: 'onboarding.complete' },
        { label: 'Онбординг: загрузка файла', value: 'onboarding.file_upload' },
        { label: 'Онбординг: минимальный набор файлов', value: 'onboarding.minimum_set_complete' },
        { label: 'Рекомендация: статус', value: 'recommendation.status_changed' },
        { label: 'Рекомендация: отзыв', value: 'recommendation.feedback' },
        { label: 'Рекомендация: текст скопирован', value: 'recommendation.text_copied' },
        { label: 'Рекомендация: просмотр', value: 'recommendation.viewed' },
        { label: 'Рекомендация: срок изменён', value: 'recommendation.due_date_changed' },
        { label: 'Задача: просрочена', value: 'task.overdue' },
        { label: 'AI: запрос', value: 'ai.request' },
        { label: 'AI: ответ', value: 'ai.response' },
        { label: 'AI: ошибка', value: 'ai.error' },
        { label: 'AI: фоллбэк', value: 'ai.fallback' },
        // v3.3.1 — classification & wizard state machine.
        { label: 'Классификация: старт', value: 'classification.started' },
        { label: 'Классификация: завершена', value: 'classification.completed' },
        { label: 'Классификация: подтверждена юзером', value: 'classification.confirmed' },
        { label: 'Классификация: ручной override', value: 'classification.user_override' },
        { label: 'Классификация: запрошены доп.данные', value: 'classification.additional_data_requested' },
        { label: 'Классификация: выбор юзера в развилке', value: 'classification.user_choice' },
        { label: 'Классификация: degraded принят', value: 'classification.degraded_accepted' },
        { label: 'Классификация: отказ → ручной выбор', value: 'classification.refused_manual_override' },
        { label: 'Классификация: отказ → запрос поддержки', value: 'classification.refused_contact_requested' },
        { label: 'Wizard: смена состояния', value: 'wizard.state_changed' },
        { label: 'Wizard: пауза', value: 'wizard.paused' },
        { label: 'Wizard: возврат', value: 'wizard.resumed' },
        { label: 'Wizard: брошен', value: 'wizard.abandoned' },
        { label: 'Файл: распознавание начато', value: 'file.recognition_started' },
        { label: 'Файл: распознавание завершено', value: 'file.recognition_completed' },
        { label: 'Файл: извлечение начато', value: 'file.extraction_started' },
        { label: 'Файл: извлечение завершено', value: 'file.extraction_completed' },
        { label: 'Файл: ошибка парсинга', value: 'file.parse_error' },
        { label: 'Просмотр страницы', value: 'page.view' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'entityType',
      type: 'text',
      label: 'Тип сущности',
    },
    {
      name: 'entityId',
      type: 'text',
      label: 'ID сущности',
    },
    {
      name: 'payload',
      type: 'json',
      label: 'Данные',
    },
  ],
}
