/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'uploaded-files': UploadedFile;
    recommendations: Recommendation;
    'recommendation-feedback': RecommendationFeedback;
    'analysis-results': AnalysisResult;
    'ai-prompts': AiPrompt;
    'ai-usage-logs': AiUsageLog;
    'event-log': EventLog;
    'invite-codes': InviteCode;
    'access-requests': AccessRequest;
    'onboarding-funnel-events': OnboardingFunnelEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'uploaded-files': UploadedFilesSelect<false> | UploadedFilesSelect<true>;
    recommendations: RecommendationsSelect<false> | RecommendationsSelect<true>;
    'recommendation-feedback': RecommendationFeedbackSelect<false> | RecommendationFeedbackSelect<true>;
    'analysis-results': AnalysisResultsSelect<false> | AnalysisResultsSelect<true>;
    'ai-prompts': AiPromptsSelect<false> | AiPromptsSelect<true>;
    'ai-usage-logs': AiUsageLogsSelect<false> | AiUsageLogsSelect<true>;
    'event-log': EventLogSelect<false> | EventLogSelect<true>;
    'invite-codes': InviteCodesSelect<false> | InviteCodesSelect<true>;
    'access-requests': AccessRequestsSelect<false> | AccessRequestsSelect<true>;
    'onboarding-funnel-events': OnboardingFunnelEventsSelect<false> | OnboardingFunnelEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'global-settings': GlobalSetting;
  };
  globalsSelect: {
    'global-settings': GlobalSettingsSelect<false> | GlobalSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'ceo';
  mode: 'trial' | 'full' | 'expired';
  hasCompletedOnboarding?: boolean | null;
  trialExpiresAt?: string | null;
  analysisStatus?: ('none' | 'processing' | 'complete' | 'error') | null;
  inviteCode?: string | null;
  companyName?: string | null;
  inn?: string | null;
  companyType?: ('ip' | 'ooo') | null;
  wizardState:
    | 'idle'
    | 'uploading'
    | 'recognizing'
    | 'extracting'
    | 'classifying'
    | 'awaiting_confirmation'
    | 'awaiting_additional_files'
    | 'classification_refused'
    | 'analyzing'
    | 'enhancing'
    | 'completed';
  /**
   * Сколько раз AI-классификация запускалась в текущем онбординге. Сбрасывается при старте нового онбординга.
   */
  currentClassificationAttempts?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uploaded-files".
 */
export interface UploadedFile {
  id: string;
  owner: string | User;
  originalName?: string | null;
  detectedType?: string | null;
  accountCode?: string | null;
  period?: string | null;
  parseStatus?:
    | (
        | 'pending'
        | 'recognizing'
        | 'parsing'
        | 'needs_ai_recognition'
        | 'needs_ai_extraction'
        | 'success'
        | 'warning'
        | 'error'
      )
    | null;
  parseErrors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  parsedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiRecognitionLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations".
 */
export interface Recommendation {
  id: string;
  owner: string | User;
  ruleCode: string;
  ruleName: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  shortRecommendation?: string | null;
  fullText?: string | null;
  status: 'new' | 'in_progress' | 'resolved' | 'stuck' | 'dismissed';
  impactMetric?: ('accounts_receivable' | 'accounts_payable' | 'inventory' | 'revenue' | 'strategic') | null;
  impactDirection?: ('decrease' | 'increase') | null;
  impactAmount?: number | null;
  sourceAccount?: string | null;
  counterparty?: string | null;
  recipient: string;
  isDemo?: boolean | null;
  isAiGenerated?: boolean | null;
  aiEnhanced?: boolean | null;
  /**
   * Структурированные данные для AI-анализа кандидата
   */
  signals?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiEnhanceFailedAt?: string | null;
  aiEnhanceError?: string | null;
  takenAt?: string | null;
  dueDate?: string | null;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendation-feedback".
 */
export interface RecommendationFeedback {
  id: string;
  owner: string | User;
  recommendation: string | Recommendation;
  rating: 'positive' | 'negative';
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analysis-results".
 */
export interface AnalysisResult {
  id: string;
  owner: string | User;
  period: string;
  revenue?: number | null;
  cogs?: number | null;
  grossProfit?: number | null;
  grossMargin?: number | null;
  accountsReceivable?: number | null;
  accountsPayable?: number | null;
  inventory?: number | null;
  shippedGoods?: number | null;
  arTurnoverDays?: number | null;
  apTurnoverDays?: number | null;
  inventoryTurnoverDays?: number | null;
  healthIndex?: ('fine' | 'issues' | 'risky') | null;
  topDebtors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  topCreditors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiAuditSummary?: string | null;
  analysisPhase?: ('classifying' | 'rules_done' | 'ai_pending' | 'ai_complete' | 'ai_error') | null;
  isDemo?: boolean | null;
  businessModel?:
    | (
        | 'project'
        | 'trading'
        | 'production'
        | 'subscription'
        | 'consulting'
        | 'agency'
        | 'project_trading'
        | 'production_project'
        | 'consulting_subscription'
        | 'trading_agency'
        | 'subscription_consulting'
        | 'production_trading'
        | 'clinic'
      )
    | null;
  businessModelConfidence?: number | null;
  businessModelRationale?: string | null;
  /**
   * inventory_balance_41, wip_balance_20, finished_goods_43, revenue_regularity_score, fot_share_in_cogs, agency_transit_share, account_26_destination, _missing[]
   */
  businessModelIndicators?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  businessModelUserOverridden?: boolean | null;
  businessModelOriginalAi?: string | null;
  classificationStatus?: ('success' | 'degraded' | 'refused_manual' | 'disabled') | null;
  /**
   * Массив строк (кодов счетов), которые AI попросил дозагрузить для повышения точности.
   */
  requestedAdditionalAccounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  classificationAttempts?: number | null;
  /**
   * Заполняется AI, когда сигналы выглядят как гибрид, но не складываются в логичную бизнес-историю (артефакт мусора).
   */
  dataQualityWarning?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompts".
 */
export interface AiPrompt {
  id: string;
  promptKey: string;
  name: string;
  systemPrompt: string;
  userPromptTemplate?: string | null;
  version?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage-logs".
 */
export interface AiUsageLog {
  id: string;
  owner: string | User;
  promptKey: string;
  inputTokens?: number | null;
  outputTokens?: number | null;
  model?: string | null;
  cost?: number | null;
  durationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-log".
 */
export interface EventLog {
  id: string;
  owner?: (string | null) | User;
  eventType:
    | 'auth.login'
    | 'auth.logout'
    | 'access.request'
    | 'invite.used'
    | 'onboarding.analysis_start'
    | 'onboarding.analysis_complete'
    | 'onboarding.complete'
    | 'onboarding.file_upload'
    | 'onboarding.minimum_set_complete'
    | 'recommendation.status_changed'
    | 'recommendation.feedback'
    | 'recommendation.text_copied'
    | 'recommendation.viewed'
    | 'recommendation.due_date_changed'
    | 'task.overdue'
    | 'ai.request'
    | 'ai.response'
    | 'ai.error'
    | 'ai.fallback'
    | 'classification.started'
    | 'classification.completed'
    | 'classification.confirmed'
    | 'classification.user_override'
    | 'classification.additional_data_requested'
    | 'classification.user_choice'
    | 'classification.degraded_accepted'
    | 'classification.refused_manual_override'
    | 'classification.refused_contact_requested'
    | 'wizard.state_changed'
    | 'wizard.paused'
    | 'wizard.resumed'
    | 'wizard.abandoned'
    | 'file.recognition_started'
    | 'file.recognition_completed'
    | 'file.extraction_started'
    | 'file.extraction_completed'
    | 'file.parse_error'
    | 'page.view';
  entityType?: string | null;
  entityId?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes".
 */
export interface InviteCode {
  id: string;
  code: string;
  createdBy?: (string | null) | User;
  usedBy?: (string | null) | User;
  isUsed?: boolean | null;
  expiresAt?: string | null;
  channel?: ('telegram' | 'whatsapp' | 'email' | 'linkedin' | 'other') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests".
 */
export interface AccessRequest {
  id: string;
  email: string;
  status: 'pending' | 'approved' | 'rejected';
  inviteCode?: string | null;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Аналитический архив. Записи нельзя удалять (даже admin).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-funnel-events".
 */
export interface OnboardingFunnelEvent {
  id: string;
  owner: string | User;
  attemptNumber: number;
  reachedStart?: boolean | null;
  reachedUpload?: boolean | null;
  reachedMinimumSet?: boolean | null;
  reachedRecommendedSet?: boolean | null;
  reachedRecognition?: boolean | null;
  reachedExtraction?: boolean | null;
  reachedClassification?: boolean | null;
  reachedConfirmation?: boolean | null;
  reachedAnalysis?: boolean | null;
  startedAt?: string | null;
  uploadStartedAt?: string | null;
  minimumSetCompletedAt?: string | null;
  recommendedSetCompletedAt?: string | null;
  classificationStartedAt?: string | null;
  classificationCompletedAt?: string | null;
  confirmationCompletedAt?: string | null;
  analysisCompletedAt?: string | null;
  abandonedAt?: string | null;
  durationToUpload?: number | null;
  durationUpload?: number | null;
  durationRecognition?: number | null;
  durationExtraction?: number | null;
  durationClassification?: number | null;
  durationConfirmation?: number | null;
  durationAnalysis?: number | null;
  durationTotal?: number | null;
  filesUploaded?: number | null;
  /**
   * Массив строк (кодов счетов).
   */
  uploadedAccounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  missingRequiredAccounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  missingRecommendedAccounts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  classificationAttempts?: number | null;
  classificationFinalStatus?: ('success' | 'degraded' | 'refused_manual' | 'disabled') | null;
  initialAiModel?: string | null;
  initialAiConfidence?: number | null;
  finalModel?: string | null;
  finalConfidence?: number | null;
  userOverridden?: boolean | null;
  hasDataQualityWarning?: boolean | null;
  /**
   * Массив массивов: каждая попытка классификации добавляет новый ряд.
   */
  requestedAccountsHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Лог выборов в развилке: [{attempt, choice, timestamp}]
   */
  forkChoices?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pauseCount?: number | null;
  totalPauseDurationMs?: number | null;
  outcome: 'in_progress' | 'completed' | 'abandoned' | 'refused';
  recommendationsCreated?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'uploaded-files';
        value: string | UploadedFile;
      } | null)
    | ({
        relationTo: 'recommendations';
        value: string | Recommendation;
      } | null)
    | ({
        relationTo: 'recommendation-feedback';
        value: string | RecommendationFeedback;
      } | null)
    | ({
        relationTo: 'analysis-results';
        value: string | AnalysisResult;
      } | null)
    | ({
        relationTo: 'ai-prompts';
        value: string | AiPrompt;
      } | null)
    | ({
        relationTo: 'ai-usage-logs';
        value: string | AiUsageLog;
      } | null)
    | ({
        relationTo: 'event-log';
        value: string | EventLog;
      } | null)
    | ({
        relationTo: 'invite-codes';
        value: string | InviteCode;
      } | null)
    | ({
        relationTo: 'access-requests';
        value: string | AccessRequest;
      } | null)
    | ({
        relationTo: 'onboarding-funnel-events';
        value: string | OnboardingFunnelEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  mode?: T;
  hasCompletedOnboarding?: T;
  trialExpiresAt?: T;
  analysisStatus?: T;
  inviteCode?: T;
  companyName?: T;
  inn?: T;
  companyType?: T;
  wizardState?: T;
  currentClassificationAttempts?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uploaded-files_select".
 */
export interface UploadedFilesSelect<T extends boolean = true> {
  owner?: T;
  originalName?: T;
  detectedType?: T;
  accountCode?: T;
  period?: T;
  parseStatus?: T;
  parseErrors?: T;
  parsedData?: T;
  aiRecognitionLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations_select".
 */
export interface RecommendationsSelect<T extends boolean = true> {
  owner?: T;
  ruleCode?: T;
  ruleName?: T;
  priority?: T;
  title?: T;
  description?: T;
  shortRecommendation?: T;
  fullText?: T;
  status?: T;
  impactMetric?: T;
  impactDirection?: T;
  impactAmount?: T;
  sourceAccount?: T;
  counterparty?: T;
  recipient?: T;
  isDemo?: T;
  isAiGenerated?: T;
  aiEnhanced?: T;
  signals?: T;
  aiEnhanceFailedAt?: T;
  aiEnhanceError?: T;
  takenAt?: T;
  dueDate?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendation-feedback_select".
 */
export interface RecommendationFeedbackSelect<T extends boolean = true> {
  owner?: T;
  recommendation?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analysis-results_select".
 */
export interface AnalysisResultsSelect<T extends boolean = true> {
  owner?: T;
  period?: T;
  revenue?: T;
  cogs?: T;
  grossProfit?: T;
  grossMargin?: T;
  accountsReceivable?: T;
  accountsPayable?: T;
  inventory?: T;
  shippedGoods?: T;
  arTurnoverDays?: T;
  apTurnoverDays?: T;
  inventoryTurnoverDays?: T;
  healthIndex?: T;
  topDebtors?: T;
  topCreditors?: T;
  aiAuditSummary?: T;
  analysisPhase?: T;
  isDemo?: T;
  businessModel?: T;
  businessModelConfidence?: T;
  businessModelRationale?: T;
  businessModelIndicators?: T;
  businessModelUserOverridden?: T;
  businessModelOriginalAi?: T;
  classificationStatus?: T;
  requestedAdditionalAccounts?: T;
  classificationAttempts?: T;
  dataQualityWarning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-prompts_select".
 */
export interface AiPromptsSelect<T extends boolean = true> {
  promptKey?: T;
  name?: T;
  systemPrompt?: T;
  userPromptTemplate?: T;
  version?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage-logs_select".
 */
export interface AiUsageLogsSelect<T extends boolean = true> {
  owner?: T;
  promptKey?: T;
  inputTokens?: T;
  outputTokens?: T;
  model?: T;
  cost?: T;
  durationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-log_select".
 */
export interface EventLogSelect<T extends boolean = true> {
  owner?: T;
  eventType?: T;
  entityType?: T;
  entityId?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-codes_select".
 */
export interface InviteCodesSelect<T extends boolean = true> {
  code?: T;
  createdBy?: T;
  usedBy?: T;
  isUsed?: T;
  expiresAt?: T;
  channel?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests_select".
 */
export interface AccessRequestsSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  inviteCode?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-funnel-events_select".
 */
export interface OnboardingFunnelEventsSelect<T extends boolean = true> {
  owner?: T;
  attemptNumber?: T;
  reachedStart?: T;
  reachedUpload?: T;
  reachedMinimumSet?: T;
  reachedRecommendedSet?: T;
  reachedRecognition?: T;
  reachedExtraction?: T;
  reachedClassification?: T;
  reachedConfirmation?: T;
  reachedAnalysis?: T;
  startedAt?: T;
  uploadStartedAt?: T;
  minimumSetCompletedAt?: T;
  recommendedSetCompletedAt?: T;
  classificationStartedAt?: T;
  classificationCompletedAt?: T;
  confirmationCompletedAt?: T;
  analysisCompletedAt?: T;
  abandonedAt?: T;
  durationToUpload?: T;
  durationUpload?: T;
  durationRecognition?: T;
  durationExtraction?: T;
  durationClassification?: T;
  durationConfirmation?: T;
  durationAnalysis?: T;
  durationTotal?: T;
  filesUploaded?: T;
  uploadedAccounts?: T;
  missingRequiredAccounts?: T;
  missingRecommendedAccounts?: T;
  classificationAttempts?: T;
  classificationFinalStatus?: T;
  initialAiModel?: T;
  initialAiConfidence?: T;
  finalModel?: T;
  finalConfidence?: T;
  userOverridden?: T;
  hasDataQualityWarning?: T;
  requestedAccountsHistory?: T;
  forkChoices?: T;
  pauseCount?: T;
  totalPauseDurationMs?: T;
  outcome?: T;
  recommendationsCreated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-settings".
 */
export interface GlobalSetting {
  id: string;
  aiEnabled?: boolean | null;
  aiProvider?: ('anthropic' | 'openai') | null;
  aiModel?: string | null;
  trialDays?: number | null;
  /**
   * Если выключено — все правила используют статические шаблоны
   */
  aiRulesEnabled?: boolean | null;
  /**
   * Выберите, какие правила обогащать AI. Остальные используют шаблоны.
   */
  aiRulesEnabledFor?: ('ДЗ-1' | 'ДЗ-2' | 'ДЗ-3' | 'КЗ-1' | 'ЗАП-1' | 'ЗАП-2' | 'ПЛ-1' | 'ФЦ-1' | 'СВС-1')[] | null;
  /**
   * Сколько кандидатов обрабатывается за один вызов /ai-enhance-batch (Vercel Hobby: 2-3, Pro: 5-8)
   */
  aiRulesBatchSize?: number | null;
  /**
   * Если выключено — нестандартные форматы CSV отбрасываются с предупреждением, как раньше
   */
  aiFileExtractionEnabled?: boolean | null;
  /**
   * Файлы больше лимита будут обрезаны перед отправкой в AI (Phase 2)
   */
  aiFileExtractionMaxKB?: number | null;
  /**
   * Файлов на один вызов /api/files/ai-recognize-batch (Vercel Hobby: 2, Pro: 3-5)
   */
  aiFileBatchSize?: number | null;
  /**
   * Если выключено — все юзеры классифицируются как «Торговая» и применяются все 9 правил (поведение v3.2)
   */
  aiClassificationEnabled?: boolean | null;
  /**
   * Ниже этого порога юзер обязательно подтверждает модель вручную
   */
  classificationConfidenceThreshold?: number | null;
  /**
   * При confidence ≥ этого порога экран подтверждения автоматически закрывается через 3 сек
   */
  classificationAutoConfirmThreshold?: number | null;
  /**
   * Если включено — при высокой уверенности юзер пропускает экран подтверждения автоматически
   */
  classificationAutoConfirmEnabled?: boolean | null;
  /**
   * После этого числа попыток — только продолжение в degraded-режиме (без новой развилки)
   */
  maxClassificationAttempts?: number | null;
  /**
   * Email или ссылка для связи при отказе классификации (например: support@mmlabs.ru)
   */
  supportContact?: string | null;
  /**
   * Минимальный набор счетов, без которых онбординг не начнётся
   */
  requiredAccountCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Повышают точность классификации, но не блокируют процесс
   */
  recommendedAccountCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Для будущего анализа ликвидности и т.п.
   */
  optionalAccountCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-settings_select".
 */
export interface GlobalSettingsSelect<T extends boolean = true> {
  aiEnabled?: T;
  aiProvider?: T;
  aiModel?: T;
  trialDays?: T;
  aiRulesEnabled?: T;
  aiRulesEnabledFor?: T;
  aiRulesBatchSize?: T;
  aiFileExtractionEnabled?: T;
  aiFileExtractionMaxKB?: T;
  aiFileBatchSize?: T;
  aiClassificationEnabled?: T;
  classificationConfidenceThreshold?: T;
  classificationAutoConfirmThreshold?: T;
  classificationAutoConfirmEnabled?: T;
  maxClassificationAttempts?: T;
  supportContact?: T;
  requiredAccountCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  recommendedAccountCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  optionalAccountCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}